// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8w8u4gpSE4vbyCKS9W1WOfRyjVBn6DRI',
    appId: '1:794048230544:web:6b70b7c467a04c29eb9415',
    messagingSenderId: '794048230544',
    projectId: 'task-1-52837',
    authDomain: 'task-1-52837.firebaseapp.com',
    storageBucket: 'task-1-52837.appspot.com',
    measurementId: 'G-DH2XLX92V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe84gMa_U1yX-0zAJsLyIs_gBCsThgp50',
    appId: '1:794048230544:android:7422345eea623ddbeb9415',
    messagingSenderId: '794048230544',
    projectId: 'task-1-52837',
    storageBucket: 'task-1-52837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5LDBe_Kl40PYdgzLBiEtH0exJwVYlJyg',
    appId: '1:794048230544:ios:8f051c8154da7079eb9415',
    messagingSenderId: '794048230544',
    projectId: 'task-1-52837',
    storageBucket: 'task-1-52837.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5LDBe_Kl40PYdgzLBiEtH0exJwVYlJyg',
    appId: '1:794048230544:ios:8f051c8154da7079eb9415',
    messagingSenderId: '794048230544',
    projectId: 'task-1-52837',
    storageBucket: 'task-1-52837.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8w8u4gpSE4vbyCKS9W1WOfRyjVBn6DRI',
    appId: '1:794048230544:web:5ffc3d86bb992241eb9415',
    messagingSenderId: '794048230544',
    projectId: 'task-1-52837',
    authDomain: 'task-1-52837.firebaseapp.com',
    storageBucket: 'task-1-52837.appspot.com',
    measurementId: 'G-M25DXS334B',
  );

}